[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
